version: '3'

services:
   web:
      depends_on:
         - api
      build: ./frontend
      ports:
         - 5173:3000

      develop:
         watch:
            -  path: ./frontend/package.json
               action: rebuild

            -  path: ./frontend/package.lock.json
               action: rebuild

            -  path: ./frontend
               target: /app
               action: sync


   api:
      depends_on:
         - db
      build: ./backend
      ports:
         - 5000:5000
      environment:
         - NODE_ENV=development
      
      develop:
         watch: 
            -  path: ./backend/package.json
               action: rebuild

            -  path: ./backend/package.lock.json
               action: rebuild
            
            -  path: ./backend
               target: /app
               action: sync
   
   db:
      image: mongo:latest
      ports:
         - 27017:27017
      volumes:
         - ./data/:/data/db